{"topicSections":[{"identifiers":["doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYProgress","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/Transaction"],"generated":true,"anchor":"Classes","title":"Classes"},{"title":"Protocols","identifiers":["doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYProgressView","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/Appearance","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/SecurityWarningsDelegate"],"anchor":"Protocols","generated":true},{"identifiers":["doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/AppearanceConfiguration","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/AuthenticationRequestParameters","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ButtonAppearance","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ChallengeParameters","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ChallengeResult","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/InfoAppearance","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/LabelAppearance","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/NavigationBarAppearance","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/SelectAppearance","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ServiceParameters","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/SwitchAppearance","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/TextFieldAppearance","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ThreeDSError","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/Warning"],"title":"Structures","generated":true,"anchor":"Structures"},{"identifiers":["doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADY3DS2SDKVersion()","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/SDKVersion()"],"anchor":"Functions","title":"Functions","generated":true},{"generated":true,"identifiers":["doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/AppearanceButtonType","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ButtonAppearanceTextTransform","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ErrorType","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/LegacyInterface","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/MessageVersion","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/WarningSeverity"],"title":"Enumerations","anchor":"Enumerations"},{"title":"Extended Modules","generated":true,"identifiers":["doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/Foundation","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/UIKit"],"anchor":"Extended-Modules"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"Adyen3DS2_Swift","roleHeading":"Framework","role":"collection","modules":[{"name":"Adyen3DS2_Swift"}],"title":"Adyen3DS2_Swift","symbolKind":"module"},"hierarchy":{"paths":[[]]},"identifier":{"url":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/adyen3ds2_swift"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/adyen3ds2_swift"]}],"sections":[],"kind":"symbol","references":{"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/AuthenticationRequestParameters":{"kind":"symbol","url":"\/documentation\/adyen3ds2_swift\/authenticationrequestparameters","navigatorTitle":[{"text":"AuthenticationRequestParameters","kind":"identifier"}],"title":"AuthenticationRequestParameters","type":"topic","identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/AuthenticationRequestParameters","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationRequestParameters"}],"role":"symbol","abstract":[{"type":"text","text":"Contains data that should be sent to the 3DS Server in an authentication request (AReq)."}]},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/LabelAppearance":{"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/LabelAppearance","role":"symbol","type":"topic","url":"\/documentation\/adyen3ds2_swift\/labelappearance","kind":"symbol","title":"LabelAppearance","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LabelAppearance","kind":"identifier"}],"abstract":[{"type":"text","text":"Contains properties to customize the appearance of the labels."}],"navigatorTitle":[{"text":"LabelAppearance","kind":"identifier"}]},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/ErrorType":{"kind":"symbol","url":"\/documentation\/adyen3ds2_swift\/errortype","navigatorTitle":[{"text":"ErrorType","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The Error type"}],"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ErrorType","type":"topic","title":"ErrorType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorType","kind":"identifier"}]},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/ButtonAppearanceTextTransform":{"role":"symbol","url":"\/documentation\/adyen3ds2_swift\/buttonappearancetexttransform","kind":"symbol","navigatorTitle":[{"text":"ButtonAppearanceTextTransform","kind":"identifier"}],"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ButtonAppearanceTextTransform","abstract":[{"text":"The type of transform to apply to the button’s text.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ButtonAppearanceTextTransform","kind":"identifier"}],"title":"ButtonAppearanceTextTransform","type":"topic"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/NavigationBarAppearance":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NavigationBarAppearance"}],"type":"topic","kind":"symbol","title":"NavigationBarAppearance","role":"symbol","navigatorTitle":[{"text":"NavigationBarAppearance","kind":"identifier"}],"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/NavigationBarAppearance","url":"\/documentation\/adyen3ds2_swift\/navigationbarappearance","abstract":[{"type":"text","text":"Contains properties to customize the appearance of the navigation bar."}]},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/ButtonAppearance":{"url":"\/documentation\/adyen3ds2_swift\/buttonappearance","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ButtonAppearance","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"ButtonAppearance","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ButtonAppearance"}],"type":"topic","abstract":[{"text":"Contains properties to customize the appearance of a button.","type":"text"}],"title":"ButtonAppearance"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/ServiceParameters":{"kind":"symbol","url":"\/documentation\/adyen3ds2_swift\/serviceparameters","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"ServiceParameters","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ServiceParameters","title":"ServiceParameters","role":"symbol","abstract":[{"text":"A collection of parameters used during the initialization of the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/Transaction"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"ServiceParameters","kind":"identifier"}]},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/Appearance":{"role":"symbol","abstract":[{"type":"text","text":"Contains properties to customize the appearance of an interface element."}],"title":"Appearance","kind":"symbol","identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/Appearance","url":"\/documentation\/adyen3ds2_swift\/appearance","navigatorTitle":[{"text":"Appearance","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Appearance"}]},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/Transaction":{"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/Transaction","kind":"symbol","role":"symbol","abstract":[{"text":"Represents a transaction that is to be authenticated using 3D-Secure 2.0.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Transaction","kind":"identifier"}],"type":"topic","title":"Transaction","navigatorTitle":[{"text":"Transaction","kind":"identifier"}],"url":"\/documentation\/adyen3ds2_swift\/transaction"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/ThreeDSError":{"type":"topic","navigatorTitle":[{"text":"ThreeDSError","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Describes any error that can be thrown during a Three DS 2.0 Transaction.","type":"text"}],"title":"ThreeDSError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThreeDSError"}],"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ThreeDSError","url":"\/documentation\/adyen3ds2_swift\/threedserror","kind":"symbol"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/AppearanceConfiguration":{"title":"AppearanceConfiguration","abstract":[{"text":"Provides appearance customization properties for interface elements used throughout the challenge flow.","type":"text"}],"url":"\/documentation\/adyen3ds2_swift\/appearanceconfiguration","navigatorTitle":[{"kind":"identifier","text":"AppearanceConfiguration"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"AppearanceConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/AppearanceConfiguration","type":"topic"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift":{"type":"topic","url":"\/documentation\/adyen3ds2_swift","identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift","role":"collection","kind":"symbol","abstract":[],"title":"Adyen3DS2_Swift"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/TextFieldAppearance":{"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TextFieldAppearance"}],"kind":"symbol","title":"TextFieldAppearance","role":"symbol","url":"\/documentation\/adyen3ds2_swift\/textfieldappearance","identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/TextFieldAppearance","navigatorTitle":[{"text":"TextFieldAppearance","kind":"identifier"}],"abstract":[{"text":"Contains properties to customize the appearance of the text fields.","type":"text"}]},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/Warning":{"abstract":[{"type":"text","text":"Describes a warning produced while conducting security checks."}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Warning","kind":"identifier"}],"url":"\/documentation\/adyen3ds2_swift\/warning","type":"topic","kind":"symbol","title":"Warning","identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/Warning","navigatorTitle":[{"kind":"identifier","text":"Warning"}]},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/ChallengeParameters":{"title":"ChallengeParameters","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChallengeParameters"}],"type":"topic","url":"\/documentation\/adyen3ds2_swift\/challengeparameters","abstract":[{"type":"text","text":"Contains data returned by the 3DS Server in response to an authentication request (AReq)."}],"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ChallengeParameters","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChallengeParameters"}]},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/SDKVersion()":{"url":"\/documentation\/adyen3ds2_swift\/sdkversion()","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKVersion"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"SDKVersion()","abstract":[],"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/SDKVersion()","type":"topic"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/ADYProgress":{"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYProgress","url":"\/documentation\/adyen3ds2_swift\/adyprogress","title":"ADYProgress","role":"symbol","type":"topic","deprecated":true,"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ADYProgress"}],"navigatorTitle":[{"kind":"identifier","text":"ADYProgress"}]},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/ADY3DS2SDKVersion()":{"title":"ADY3DS2SDKVersion()","abstract":[],"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADY3DS2SDKVersion()","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ADY3DS2SDKVersion"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/adyen3ds2_swift\/ady3ds2sdkversion()","deprecated":true},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/UIKit":{"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/UIKit","abstract":[],"role":"collection","title":"UIKit","kind":"symbol","url":"\/documentation\/adyen3ds2_swift\/uikit","type":"topic"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/Adyen3DS2_SwiftVersionNumber":{"kind":"symbol","identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/Adyen3DS2_SwiftVersionNumber","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"Adyen3DS2_SwiftVersionNumber"}],"url":"\/documentation\/adyen3ds2_swift\/adyen3ds2_swiftversionnumber","abstract":[{"type":"text","text":"Project version number for Adyen3DS2_Swift."}],"title":"Adyen3DS2_SwiftVersionNumber"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/SwitchAppearance":{"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/SwitchAppearance","navigatorTitle":[{"kind":"identifier","text":"SwitchAppearance"}],"title":"SwitchAppearance","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SwitchAppearance"}],"url":"\/documentation\/adyen3ds2_swift\/switchappearance","type":"topic","abstract":[]},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/WarningSeverity":{"kind":"symbol","identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/WarningSeverity","abstract":[{"text":"Enum describing the severity levels of warnings produced while conducting security checks.","type":"text"}],"title":"WarningSeverity","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WarningSeverity"}],"url":"\/documentation\/adyen3ds2_swift\/warningseverity","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WarningSeverity"}],"role":"symbol"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/MessageVersion":{"url":"\/documentation\/adyen3ds2_swift\/messageversion","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageVersion"}],"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/MessageVersion","navigatorTitle":[{"text":"MessageVersion","kind":"identifier"}],"role":"symbol","abstract":[],"title":"MessageVersion"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/ChallengeResult":{"kind":"symbol","type":"topic","url":"\/documentation\/adyen3ds2_swift\/challengeresult","title":"ChallengeResult","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChallengeResult"}],"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ChallengeResult","role":"symbol","abstract":[{"type":"text","text":"Contains the result of a successfully completed challenge."}],"navigatorTitle":[{"text":"ChallengeResult","kind":"identifier"}]},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/ADYProgressView":{"type":"topic","role":"symbol","title":"ADYProgressView","navigatorTitle":[{"text":"ADYProgressView","kind":"identifier"}],"url":"\/documentation\/adyen3ds2_swift\/adyprogressview","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ADYProgressView","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYProgressView","deprecated":true,"kind":"symbol"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/AppearanceButtonType":{"navigatorTitle":[{"kind":"identifier","text":"AppearanceButtonType"}],"url":"\/documentation\/adyen3ds2_swift\/appearancebuttontype","identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/AppearanceButtonType","abstract":[{"type":"text","text":"An enum describing the different button types."}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AppearanceButtonType","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"AppearanceButtonType"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/SelectAppearance":{"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/SelectAppearance","title":"SelectAppearance","navigatorTitle":[{"kind":"identifier","text":"SelectAppearance"}],"abstract":[{"type":"text","text":"Contains properties to customize the appearance of select controls."}],"role":"symbol","url":"\/documentation\/adyen3ds2_swift\/selectappearance","kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SelectAppearance","kind":"identifier"}]},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/Adyen3DS2_SwiftVersionString":{"abstract":[{"text":"Project version string for Adyen3DS2_Swift.","type":"text"}],"kind":"symbol","title":"Adyen3DS2_SwiftVersionString","role":"symbol","type":"topic","identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/Adyen3DS2_SwiftVersionString","fragments":[{"text":"Adyen3DS2_SwiftVersionString","kind":"identifier"}],"url":"\/documentation\/adyen3ds2_swift\/adyen3ds2_swiftversionstring"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/Foundation":{"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/Foundation","title":"Foundation","abstract":[],"url":"\/documentation\/adyen3ds2_swift\/foundation","kind":"symbol","role":"collection","type":"topic"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/LegacyInterface":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LegacyInterface","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"LegacyInterface"}],"abstract":[],"role":"symbol","title":"LegacyInterface","identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/LegacyInterface","kind":"symbol","url":"\/documentation\/adyen3ds2_swift\/legacyinterface"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/SecurityWarningsDelegate":{"abstract":[{"type":"text","text":"A delegate to receive real time security warnings."}],"title":"SecurityWarningsDelegate","url":"\/documentation\/adyen3ds2_swift\/securitywarningsdelegate","identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/SecurityWarningsDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SecurityWarningsDelegate"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SecurityWarningsDelegate"}]},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/InfoAppearance":{"role":"symbol","abstract":[{"type":"text","text":"Contains properties to customize the appearance of info items."}],"title":"InfoAppearance","kind":"symbol","identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/InfoAppearance","url":"\/documentation\/adyen3ds2_swift\/infoappearance","navigatorTitle":[{"kind":"identifier","text":"InfoAppearance"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"InfoAppearance"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":[{"generated":true,"identifiers":["doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/Adyen3DS2_SwiftVersionNumber","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/Adyen3DS2_SwiftVersionString"],"title":"Variables","anchor":"Variables"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"}],"traits":[{"interfaceLanguage":"occ"}]}]}